apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.entityService }}
  selector:
    matchLabels:
      app: entity-service
  template:
    metadata:
      labels:
        app: entity-service
    spec:
      containers:
        - name: entity-service
          image: {{ .Values.image.entityService }}
          ports:
            - containerPort: 1290
          envFrom:
            - configMapRef:
                name: ssare-config
            - secretRef:
                name: ssare-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"