apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.ollama }}
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: {{ .Values.image.ollama }}
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"