apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-placeholder
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.peliasPlaceholder }}
  selector:
    matchLabels:
      app: pelias-placeholder
  template:
    metadata:
      labels:
        app: pelias-placeholder
    spec:
      containers:
        - name: pelias-placeholder
          image: {{ .Values.image.peliasPlaceholder }}
          ports:
            - containerPort: {{ .Values.service.peliasPlaceholder.targetPort }}
          command:
            - sh
            - -c
            - |
              if [ ! -s /data/placeholder/store.sqlite3 ]; then
                echo "Placeholder data not found or empty. Downloading..."
                rm -f /data/placeholder/store.sqlite3
                mkdir -p /data/placeholder
                wget -O /data/placeholder/store.sqlite3.gz https://data.geocode.earth/placeholder/store.sqlite3.gz
                gunzip /data/placeholder/store.sqlite3.gz
              else
                echo "Placeholder data found."
              fi
              ls -l /data/placeholder
              ./cmd/server.sh
          env:
            - name: PORT
              value: "{{ .Values.service.peliasPlaceholder.port }}"
            - name: WORKERS
              value: "8"
          volumeMounts:
            - name: pelias-placeholder-data
              mountPath: /data/placeholder
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: pelias-placeholder-data
          persistentVolumeClaim:
            claimName: pelias-placeholder-pvc