"""Add meta_summary to Content

Revision ID: 02d992e899ec
Revises: eef25b2f3ebd
Create Date: 2024-11-26 20:27:51.181324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '02d992e899ec'
down_revision = 'eef25b2f3ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###