"""Add meta_summary to Content

Revision ID: 3cd5fd4e186c
Revises: 9a6013063a11
Create Date: 2024-11-27 03:57:17.217591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '3cd5fd4e186c'
down_revision = '9a6013063a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###