"""Add meta_summary to Content

Revision ID: 6a47d86b6d63
Revises: 9f4e66db5c66
Create Date: 2024-11-26 17:25:44.373501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '6a47d86b6d63'
down_revision = '9f4e66db5c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###