"""Add meta_summary to Content

Revision ID: a90cd0c30346
Revises: 752c2eeb4cb5
Create Date: 2024-11-23 00:38:41.687840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'a90cd0c30346'
down_revision = '752c2eeb4cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###