"""Add meta_summary to Content

Revision ID: af3158e711f1
Revises: 8c90dbb2884b
Create Date: 2024-11-23 02:01:47.849838

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'af3158e711f1'
down_revision = '8c90dbb2884b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###