"""Add thematic_locations to ContentEvaluation

Revision ID: b98ec4fc49d5
Revises: c7f29139af90
Create Date: 2024-11-13 03:52:56.210924

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b98ec4fc49d5'
down_revision = 'c7f29139af90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentevaluation', sa.Column('thematic_locations', sa.ARRAY(sa.Text()), nullable=True))
    op.drop_column('contentevaluation', 'keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentevaluation', sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.drop_column('contentevaluation', 'thematic_locations')
    # ### end Alembic commands ###