"""Add meta_summary to Content

Revision ID: cd2151c20b9a
Revises: baa77bd7ad2d
Create Date: 2024-11-23 01:46:43.205844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'cd2151c20b9a'
down_revision = 'baa77bd7ad2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###