"""Add meta_summary to Content

Revision ID: cebb3ee51d2e
Revises: 5c9785b8cf43
Create Date: 2024-11-27 00:03:17.727430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'cebb3ee51d2e'
down_revision = '5c9785b8cf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###