"""Adding top locations and entities to content

Revision ID: ea93e1fa0b6d
Revises: 44aa45634e6a
Create Date: 2024-12-04 20:28:28.484908

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'ea93e1fa0b6d'
down_revision = '44aa45634e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###