"""Add meta_summary to Content

Revision ID: 02a13c8c2402
Revises: e59bf5e06884
Create Date: 2024-11-26 23:49:38.967008

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '02a13c8c2402'
down_revision = 'e59bf5e06884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###