"""Adding top locations and entities to content

Revision ID: 0d4d3d9cb61b
Revises: 9955f0b63b23
Create Date: 2024-12-04 19:38:00.376730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '0d4d3d9cb61b'
down_revision = '9955f0b63b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###