"""Adding top locations and entities to content

Revision ID: 1af13fa4c420
Revises: 920f2c6dd3e5
Create Date: 2024-12-04 22:35:31.605259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '1af13fa4c420'
down_revision = '920f2c6dd3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###