"""Add meta_summary to Content

Revision ID: 374f8dffbd5f
Revises: 82abcce1b2c2
Create Date: 2024-11-26 23:44:31.782951

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '374f8dffbd5f'
down_revision = '82abcce1b2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###