"""Add meta_summary to Content

Revision ID: 3e2577e67ddc
Revises: a7c8110b77c4
Create Date: 2024-11-22 23:44:44.673049

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '3e2577e67ddc'
down_revision = 'a7c8110b77c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###