"""Add top_image to MediaDetails

Revision ID: 3fccd1f7eb13
Revises: b98ec4fc49d5
Create Date: 2024-11-18 11:12:16.207192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '3fccd1f7eb13'
down_revision = 'b98ec4fc49d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediadetails', sa.Column('top_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediadetails', 'top_image')
    # ### end Alembic commands ###