"""Add meta_summary to Content

Revision ID: 7cb934148ba8
Revises: 58a9b86f0ad0
Create Date: 2024-11-26 20:10:41.254234

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '7cb934148ba8'
down_revision = '58a9b86f0ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###