"""Add meta_summary to Content

Revision ID: 7d4cbeb2266c
Revises: 8b8e2091b810
Create Date: 2024-11-18 12:57:26.396358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '7d4cbeb2266c'
down_revision = '8b8e2091b810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###