"""Adding top locations and entities to content

Revision ID: 920f2c6dd3e5
Revises: 4df44d3fd037
Create Date: 2024-12-04 22:28:20.142034

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '920f2c6dd3e5'
down_revision = '4df44d3fd037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###