"""Adding top locations and entities to content

Revision ID: 94537e512f8b
Revises: 5b5c8338c489
Create Date: 2024-12-04 22:25:18.606286

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '94537e512f8b'
down_revision = '5b5c8338c489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###