"""Add meta_summary to Content

Revision ID: b23f4aa6bce8
Revises: 46cf2703ca1f
Create Date: 2024-11-27 10:46:40.418851

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'b23f4aa6bce8'
down_revision = '46cf2703ca1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###