"""Adding top locations and entities to content

Revision ID: c6198cae92f4
Revises: 803a8f77ca9c
Create Date: 2024-12-04 22:50:20.859084

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'c6198cae92f4'
down_revision = '803a8f77ca9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###