"""Add meta_summary to Content

Revision ID: d5ac026c5693
Revises: 8d3437a4f182
Create Date: 2024-11-27 04:18:22.186328

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'd5ac026c5693'
down_revision = '8d3437a4f182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###