apiVersion: v1
kind: Service
metadata:
  name: service-geo
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.geoService.type }}
  ports:
    - port: {{ .Values.service.geoService.port }}
      targetPort: {{ .Values.service.geoService.targetPort }}
  selector:
    app: service-geo