apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.litellm.type }}
  ports:
    - port: {{ .Values.service.litellm.port }}
      targetPort: {{ .Values.service.litellm.targetPort }}
  selector:
    app: litellm