apiVersion: v1
kind: Service
metadata:
  name: service-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.postgresService.type }}
  ports:
    - port: {{ .Values.service.postgresService.port }}
      targetPort: {{ .Values.service.postgresService.targetPort }}
  selector:
    app: service-postgres