apiVersion: v1
kind: Service
metadata:
  name: service-scraper
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.scraperService.type }}
  ports:
    - port: {{ .Values.service.scraperService.port }}
      targetPort: {{ .Values.service.scraperService.targetPort }}
  selector:
    app: service-scraper