"""Add meta_summary to Content

Revision ID: 2583708fc91e
Revises: 3190ffc3c97d
Create Date: 2024-11-27 00:50:02.812385

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '2583708fc91e'
down_revision = '3190ffc3c97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###