"""Add meta_summary to Content

Revision ID: 74027dbc8491
Revises: 2fa2ddd0ada9
Create Date: 2024-11-22 23:10:06.196760

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '74027dbc8491'
down_revision = '2fa2ddd0ada9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###