"""Add meta_summary to Content

Revision ID: 77548a13ce07
Revises: e9d3b7d0bae7
Create Date: 2024-11-18 19:06:57.186991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '77548a13ce07'
down_revision = 'e9d3b7d0bae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###