"""Add meta_summary to Content

Revision ID: be7d6f6f5a6d
Revises: 7c5871c24de4
Create Date: 2024-11-18 19:33:42.794305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'be7d6f6f5a6d'
down_revision = '7c5871c24de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###