"""Adding top locations and entities to content

Revision ID: bff17f1c44d4
Revises: d0d4fc7f3c03
Create Date: 2024-12-04 22:17:36.552831

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'bff17f1c44d4'
down_revision = 'd0d4fc7f3c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###