apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.embeddingService.type }}
  ports:
    - port: {{ .Values.service.embeddingService.port }}
      targetPort: {{ .Values.service.embeddingService.targetPort }}
  selector:
    app: embedding-service