apiVersion: v1
kind: Service
metadata:
  name: pelias-placeholder
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.peliasPlaceholder.type }}
  ports:
    - port: {{ .Values.service.peliasPlaceholder.port }}
      targetPort: {{ .Values.service.peliasPlaceholder.targetPort }}
  selector:
    app: pelias-placeholder