apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.traefik.type }}
  ports:
    - name: web
      port: {{ .Values.service.traefik.port }}
      targetPort: {{ .Values.service.traefik.targetPort }}
    - name: websecure
      port: {{ .Values.service.traefik.securePort }}
      targetPort: {{ .Values.service.traefik.targetSecurePort }}
  selector:
    app: traefik