"""Add top_image to MediaDetails

Revision ID: 025d263ae03f
Revises: dd446e72e7bb
Create Date: 2024-11-18 11:15:26.646486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '025d263ae03f'
down_revision = 'dd446e72e7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###