"""Add meta_summary to Content

Revision ID: 07a6823a9b70
Revises: 2879d79dbc75
Create Date: 2024-11-18 19:26:32.927961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '07a6823a9b70'
down_revision = '2879d79dbc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###