"""Add meta_summary to Content

Revision ID: 0ce94a033558
Revises: aa14a26c9156
Create Date: 2024-11-18 13:00:54.609926

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '0ce94a033558'
down_revision = 'aa14a26c9156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###