"""Add meta_summary to Content

Revision ID: 0f6f84424fce
Revises: 65b8ce1fd955
Create Date: 2024-11-23 02:20:24.546204

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '0f6f84424fce'
down_revision = '65b8ce1fd955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###