"""Add meta_summary to Content

Revision ID: 15c0ab9501da
Revises: cab66f8a6f72
Create Date: 2024-11-18 20:45:37.540763

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '15c0ab9501da'
down_revision = 'cab66f8a6f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###