"""Add meta_summary to Content

Revision ID: 2693e00ebdd8
Revises: 9acea23ee655
Create Date: 2024-11-27 02:40:51.287970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '2693e00ebdd8'
down_revision = '9acea23ee655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###