"""Add meta_summary to Content

Revision ID: 2879d79dbc75
Revises: fe1ec07fcee9
Create Date: 2024-11-18 19:15:09.238645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '2879d79dbc75'
down_revision = 'fe1ec07fcee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###