"""Add meta_summary to Content

Revision ID: 2fa2ddd0ada9
Revises: e41ba1dec9d2
Create Date: 2024-11-22 23:05:49.338968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '2fa2ddd0ada9'
down_revision = 'e41ba1dec9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###