"""Add summary to Content

Revision ID: 3bc70e13128a
Revises: 07ccf54f93d7
Create Date: 2024-11-18 12:12:40.852603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '3bc70e13128a'
down_revision = '07ccf54f93d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'summary')
    # ### end Alembic commands ###