"""Add meta_summary to Content

Revision ID: 4081b1d6c18c
Revises: 3f458c846edf
Create Date: 2024-11-18 19:44:44.836702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '4081b1d6c18c'
down_revision = '3f458c846edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###