"""Add meta_summary to Content

Revision ID: 40fc57af0d25
Revises: b0fc0f2c9279
Create Date: 2024-11-26 22:37:21.011306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '40fc57af0d25'
down_revision = 'b0fc0f2c9279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###