"""Add meta_summary to Content

Revision ID: 465c33e61aa6
Revises: b57ad87880d1
Create Date: 2024-11-26 16:15:13.296883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '465c33e61aa6'
down_revision = 'b57ad87880d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###