"""Add meta_summary to Content

Revision ID: 46cf2703ca1f
Revises: 68bb15ee562d
Create Date: 2024-11-27 05:29:53.629672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '46cf2703ca1f'
down_revision = '68bb15ee562d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###