"""Add meta_summary to Content

Revision ID: 58a9b86f0ad0
Revises: 4b915851b35c
Create Date: 2024-11-26 19:54:53.255447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '58a9b86f0ad0'
down_revision = '4b915851b35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###