"""Add meta_summary to Content

Revision ID: 5c9785b8cf43
Revises: ce39cbe20eaf
Create Date: 2024-11-26 23:53:05.680412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '5c9785b8cf43'
down_revision = 'ce39cbe20eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###