"""Add meta_summary to Content

Revision ID: 63d16f220a3f
Revises: 40fc57af0d25
Create Date: 2024-11-26 22:39:36.380246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '63d16f220a3f'
down_revision = '40fc57af0d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###