"""Add meta_summary to Content

Revision ID: 68bb15ee562d
Revises: 9c0b84a91990
Create Date: 2024-11-27 05:28:27.229822

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '68bb15ee562d'
down_revision = '9c0b84a91990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###