"""Add meta_summary to Content

Revision ID: 733fae30aa71
Revises: 15c0ab9501da
Create Date: 2024-11-18 21:00:12.860109

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '733fae30aa71'
down_revision = '15c0ab9501da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###