"""Add meta_summary to Content

Revision ID: 73d7ce4823f4
Revises: 221ff48c5c63
Create Date: 2024-11-27 00:24:00.140786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '73d7ce4823f4'
down_revision = '221ff48c5c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###