"""Add meta_summary to Content

Revision ID: 747f03bedde6
Revises: 8f26fa6f57ff
Create Date: 2024-11-26 20:15:00.528624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '747f03bedde6'
down_revision = '8f26fa6f57ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###