"""Add meta_summary to Content

Revision ID: 758b0a191aa7
Revises: 6d13c94c71b5
Create Date: 2024-11-26 20:25:31.511253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '758b0a191aa7'
down_revision = '6d13c94c71b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###