"""Add meta_summary to Content

Revision ID: 80041eaef808
Revises: fb2c99a5e9b7
Create Date: 2024-11-26 14:13:16.744884

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '80041eaef808'
down_revision = 'fb2c99a5e9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###