"""Add meta_summary to Content

Revision ID: 807c4d2923d5
Revises: b7a5662b0864
Create Date: 2024-11-19 16:47:52.854672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '807c4d2923d5'
down_revision = 'b7a5662b0864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###