"""Add meta_summary to Content

Revision ID: 82abcce1b2c2
Revises: d26d7f68b326
Create Date: 2024-11-26 23:33:38.819985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '82abcce1b2c2'
down_revision = 'd26d7f68b326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###