"""Add meta_summary to Content

Revision ID: 84ca8e3cfc63
Revises: c12ae5fe1416
Create Date: 2024-11-27 02:30:54.093690

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '84ca8e3cfc63'
down_revision = 'c12ae5fe1416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###