"""Add meta_summary to Content

Revision ID: 8afb775b3210
Revises: b23f4aa6bce8
Create Date: 2024-11-27 11:06:34.354751

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '8afb775b3210'
down_revision = 'b23f4aa6bce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###