"""Add meta_summary to Content

Revision ID: 8c8d65d31cf0
Revises: 8a8692ff5196
Create Date: 2024-11-27 04:41:34.983768

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '8c8d65d31cf0'
down_revision = '8a8692ff5196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###