"""Add meta_summary to Content

Revision ID: 998ed7bdac7f
Revises: daf1db551a95
Create Date: 2024-11-23 01:30:06.308410

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '998ed7bdac7f'
down_revision = 'daf1db551a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###