"""Add meta_summary to Content

Revision ID: 9f4e66db5c66
Revises: 07cee70e5009
Create Date: 2024-11-26 17:25:09.616456

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '9f4e66db5c66'
down_revision = '07cee70e5009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###