"""Add meta_summary to Content

Revision ID: 9f5fa6db2f50
Revises: 1d4779116887
Create Date: 2024-11-26 13:50:46.799055

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '9f5fa6db2f50'
down_revision = '1d4779116887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###