"""Add meta_summary to Content

Revision ID: b0fc0f2c9279
Revises: 937e45be18a0
Create Date: 2024-11-26 22:36:10.838623

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'b0fc0f2c9279'
down_revision = '937e45be18a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###