"""Add meta_summary to Content

Revision ID: b54b10bfa1a9
Revises: 9407a4a908e0
Create Date: 2024-11-27 03:18:26.407158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'b54b10bfa1a9'
down_revision = '9407a4a908e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###