"""Add meta_summary to Content

Revision ID: bb856bd064d3
Revises: 4ab74fdb748c
Create Date: 2024-11-18 12:23:38.783137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'bb856bd064d3'
down_revision = '4ab74fdb748c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###