"""Initial migration

Revision ID: c7f29139af90
Revises: 66469acf788f
Create Date: 2024-11-11 02:49:03.630013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'c7f29139af90'
down_revision = '66469acf788f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contentevaluation', 'rhetoric',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_contentevaluation_rhetoric', table_name='contentevaluation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contentevaluation_rhetoric', 'contentevaluation', ['rhetoric'], unique=False)
    op.alter_column('contentevaluation', 'rhetoric',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###