"""Add meta_summary to Content

Revision ID: cb95c300327b
Revises: 84ca8e3cfc63
Create Date: 2024-11-27 02:31:44.872936

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'cb95c300327b'
down_revision = '84ca8e3cfc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###