"""Add meta_summary to Content

Revision ID: ce39cbe20eaf
Revises: 02a13c8c2402
Create Date: 2024-11-26 23:50:55.656013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'ce39cbe20eaf'
down_revision = '02a13c8c2402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###