"""Add meta_summary to Content

Revision ID: d7ebac17a5eb
Revises: 807c4d2923d5
Create Date: 2024-11-19 17:08:36.631153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'd7ebac17a5eb'
down_revision = '807c4d2923d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###