"""Add meta_summary to Content

Revision ID: e41ba1dec9d2
Revises: 237e71d36dfe
Create Date: 2024-11-22 20:12:53.111925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'e41ba1dec9d2'
down_revision = '237e71d36dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###