"""Add meta_summary to Content

Revision ID: edd147d874c8
Revises: be7d6f6f5a6d
Create Date: 2024-11-18 19:37:15.145704

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'edd147d874c8'
down_revision = 'be7d6f6f5a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###