"""Add meta_summary to Content

Revision ID: f6beba31d6ea
Revises: 2824d87bd79f
Create Date: 2024-11-18 18:44:13.330425

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'f6beba31d6ea'
down_revision = '2824d87bd79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###