"""Add meta_summary to Content

Revision ID: f83dad7ec1d7
Revises: 82b1e986347e
Create Date: 2024-11-26 13:47:54.537039

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'f83dad7ec1d7'
down_revision = '82b1e986347e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###