"""Add meta_summary to Content

Revision ID: f99066ac548e
Revises: 3cd5fd4e186c
Create Date: 2024-11-27 03:58:14.144107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'f99066ac548e'
down_revision = '3cd5fd4e186c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###