"""Add meta_summary to Content

Revision ID: fb2c99a5e9b7
Revises: 85238b052e65
Create Date: 2024-11-26 14:08:24.401648

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'fb2c99a5e9b7'
down_revision = '85238b052e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###