"""Add meta_summary to Content

Revision ID: fe1ec07fcee9
Revises: 77548a13ce07
Create Date: 2024-11-18 19:12:51.574461

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'fe1ec07fcee9'
down_revision = '77548a13ce07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###