apiVersion: v1
kind: Secret
metadata:
  name: ssare-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.env.secrets.OPENAI_API_KEY | b64enc }}
  PREFECT_API_KEY: {{ .Values.env.secrets.PREFECT_API_KEY | b64enc }}
  POSTGRES_USER: {{ .Values.env.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.secrets.POSTGRES_PASSWORD | b64enc }}