apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-embeddings
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.embeddingService }}
  selector:
    matchLabels:
      app: service-embeddings
  template:
    metadata:
      labels:
        app: service-embeddings
    spec:
      containers:
        - name: service-embeddings
          image: {{ .Values.image.embeddingService }}
          ports:
            - containerPort: 420
          envFrom:
            - configMapRef:
                name: opol-config
            - secretRef:
                name: opol-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PREFECT_API_URL
              value: "{{ .Values.env.config.PREFECT_API_URL }}"
            # Add other environment variables as needed
          dependsOn:
            - service-postgres