apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-entities
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.entityService }}
  selector:
    matchLabels:
      app: service-entities
  template:
    metadata:
      labels:
        app: service-entities
    spec:
      containers:
        - name: service-entities
          image: {{ .Values.image.entityService }}
          ports:
            - containerPort: 1290
          envFrom:
            - configMapRef:
                name: opol-config
            - secretRef:
                name: opol-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"