apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-geo
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.geoService }}
  selector:
    matchLabels:
      app: service-geo
  template:
    metadata:
      labels:
        app: service-geo
    spec:
      containers:
        - name: service-geo
          image: {{ .Values.image.geoService }}
          ports:
            - containerPort: 3690
          envFrom:
            - configMapRef:
                name: opol-config
            - secretRef:
                name: opol-secrets
          expose:
            - 3690
          volumeMounts:
            - name: service-geo-volume
              mountPath: /app/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"