apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.postgresService }}
  selector:
    matchLabels:
      app: service-postgres
  template:
    metadata:
      labels:
        app: service-postgres
    spec:
      containers:
        - name: service-postgres
          image: {{ .Values.image.postgresService }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: opol-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opol-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "opol_db"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: service-postgres-pvc