apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-scraper
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.scraperService }}
  selector:
    matchLabels:
      app: service-scraper
  template:
    metadata:
      labels:
        app: service-scraper
    spec:
      containers:
        - name: service-scraper
          image: {{ .Values.image.scraperService }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: opol-config
            - secretRef:
                name: opol-secrets
          env:
            - name: PREFECT_API_URL
              value: "{{ .Values.env.config.PREFECT_API_URL }}"
            - name: PREFECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opol-secrets
                  key: PREFECT_API_KEY
            - name: PREFECT_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  name: opol-secrets
                  key: PREFECT_WORKSPACE_ID
            - name: PREFECT_WORKSPACE
              valueFrom:
                secretKeyRef:
                  name: opol-secrets
                  key: PREFECT_WORKSPACE
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"