"""Add meta_summary to Content

Revision ID: 06c77c392f1b
Revises: 9a5a89094868
Create Date: 2024-11-23 01:06:33.995965

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '06c77c392f1b'
down_revision = '9a5a89094868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###