"""Add meta_summary to Content

Revision ID: 2824d87bd79f
Revises: 1ad2f14649fb
Create Date: 2024-11-18 18:41:44.271176

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '2824d87bd79f'
down_revision = '1ad2f14649fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###