"""Add meta_summary to Content

Revision ID: 372cc239d403
Revises: 69ec1ae2e2ab
Create Date: 2024-11-18 14:44:49.947040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '372cc239d403'
down_revision = '69ec1ae2e2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###