"""Add meta_summary to Content

Revision ID: 504ab7c7f378
Revises: 8dedc33a94ef
Create Date: 2024-11-18 20:07:08.960250

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '504ab7c7f378'
down_revision = '8dedc33a94ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###