"""Add meta_summary to Content

Revision ID: 5b214b35c56b
Revises: 0b69d4f3de57
Create Date: 2024-11-27 03:53:20.507538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '5b214b35c56b'
down_revision = '0b69d4f3de57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###