"""Add meta_summary to Content

Revision ID: 6d13c94c71b5
Revises: fe3589a064d8
Create Date: 2024-11-26 20:24:19.460413

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '6d13c94c71b5'
down_revision = 'fe3589a064d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###