"""Add meta_summary to Content

Revision ID: baa08a54c9e8
Revises: ea3d53922688
Create Date: 2024-11-26 14:48:27.011384

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'baa08a54c9e8'
down_revision = 'ea3d53922688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###