"""Add meta_summary to Content

Revision ID: bc57a339c5f1
Revises: 2ffc8b277119
Create Date: 2024-11-18 14:56:06.797268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'bc57a339c5f1'
down_revision = '2ffc8b277119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###