"""Add meta_summary to Content

Revision ID: fa7ebf33d0d4
Revises: ae1057fae5c2
Create Date: 2024-11-26 22:46:04.568135

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'fa7ebf33d0d4'
down_revision = 'ae1057fae5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###