"""Add meta_summary to Content

Revision ID: 3b4b1578214b
Revises: a2c9028a8242
Create Date: 2024-11-27 03:31:35.044201

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '3b4b1578214b'
down_revision = 'a2c9028a8242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###