"""Add meta_summary to Content

Revision ID: 640ea0e5eb68
Revises: db320d4f9d66
Create Date: 2024-11-27 02:38:16.719411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '640ea0e5eb68'
down_revision = 'db320d4f9d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###