"""Add meta_summary to Content

Revision ID: 8c90dbb2884b
Revises: cd2151c20b9a
Create Date: 2024-11-23 01:50:57.432641

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '8c90dbb2884b'
down_revision = 'cd2151c20b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###