"""Add meta_summary to Content

Revision ID: 98b6a80a7dd1
Revises: 3bc70e13128a
Create Date: 2024-11-18 12:16:47.508838

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '98b6a80a7dd1'
down_revision = '3bc70e13128a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('meta_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'meta_summary')
    # ### end Alembic commands ###