"""Add meta_summary to Content

Revision ID: baa77bd7ad2d
Revises: 6ff92b579eea
Create Date: 2024-11-23 01:45:11.579925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'baa77bd7ad2d'
down_revision = '6ff92b579eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###