"""Add meta_summary to Content

Revision ID: cc3648f34b4e
Revises: 5b214b35c56b
Create Date: 2024-11-27 03:55:27.408889

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'cc3648f34b4e'
down_revision = '5b214b35c56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###