"""Add meta_summary to Content

Revision ID: d1e07e581eaa
Revises: 3b4b1578214b
Create Date: 2024-11-27 03:33:52.536449

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'd1e07e581eaa'
down_revision = '3b4b1578214b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###