"""Add meta_summary to Content

Revision ID: 1456fe19e1b0
Revises: 9f5fa6db2f50
Create Date: 2024-11-26 13:52:37.475382

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '1456fe19e1b0'
down_revision = '9f5fa6db2f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###