"""Add meta_summary to Content

Revision ID: 19df9d7fef4a
Revises: cb95c300327b
Create Date: 2024-11-27 02:32:50.664407

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '19df9d7fef4a'
down_revision = 'cb95c300327b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###