"""Add meta_summary to Content

Revision ID: 69ec1ae2e2ab
Revises: 7d7db9c4e89f
Create Date: 2024-11-18 14:40:25.268178

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '69ec1ae2e2ab'
down_revision = '7d7db9c4e89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###