"""Add meta_summary to Content

Revision ID: 8f26fa6f57ff
Revises: 7cb934148ba8
Create Date: 2024-11-26 20:13:15.345432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '8f26fa6f57ff'
down_revision = '7cb934148ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###