"""Add meta_summary to Content

Revision ID: e9d3b7d0bae7
Revises: af02a541f23a
Create Date: 2024-11-18 18:59:28.354979

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'e9d3b7d0bae7'
down_revision = 'af02a541f23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###