"""Add meta_summary to Content

Revision ID: f2fab1ee1d08
Revises: 06c77c392f1b
Create Date: 2024-11-23 01:08:39.250273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'f2fab1ee1d08'
down_revision = '06c77c392f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###