apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-entity-service
spec:
  selector:
    app: entity-service
  ports:
    - port: {{ .Values.entityService.port }}
      targetPort: {{ .Values.entityService.port }}