name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and Push Entities Flow
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:${{ github.sha }} -f ./entity-service/Dockerfile --target flow .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:latest

      - name: Build and Push Custom LiteLLM
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/custom-litellm:${{ github.sha }} -f ./litellm/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/custom-litellm:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/custom-litellm:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/custom-litellm:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/custom-litellm:latest

      - name: Build and Push Entity Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/entity-service:${{ github.sha }} -f ./entity-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entity-service:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/entity-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/entity-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entity-service:latest

      - name: Build and Push Geo Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/geo-service:${{ github.sha }} -f ./geo-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/geo-service:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/geo-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/geo-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/geo-service:latest

      - name: Build and Push Main Core App
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/opol-core-app:${{ github.sha }} -f ./app/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/opol-core-app:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/opol-core-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/opol-core-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/opol-core-app:latest

      - name: Build and Push Embedding Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/embedding-service:${{ github.sha }} -f ./embeddingservice/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/embedding-service:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/embedding-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/embedding-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/embedding-service:latest

      - name: Build and Push Postgres Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/postgres-service:${{ github.sha }} -f ./postgres-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres-service:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/postgres-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/postgres-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres-service:latest


      - name: Build and Push Scraper Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scraper-service:${{ github.sha }} -f ./scraper-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper-service:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/scraper-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/scraper-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper-service:latest

      - name: Build and Push Classification Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/classificationservice:${{ github.sha }} -f ./classification-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/classificationservice:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/classificationservice:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/classificationservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/classificationservice:latest


      - name: Build and Push Embedding Flow
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/embedding-flow:${{ github.sha }} -f ./embeddingservice/Dockerfile --target flow .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/embedding-flow:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/embedding-flow:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/embedding-flow:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/embedding-flow:latest

      - name: Build and Push Scraper Flow
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scraper-flow:${{ github.sha }} -f ./scraper-service/Dockerfile --target flow .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper-flow:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/scraper-flow:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/scraper-flow:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper-flow:latest

      - name: Build and Push Entities Flow
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:${{ github.sha }} -f ./entity-service/Dockerfile --target flow .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entities-flow:latest

      - name: Build and Push Ray Worker
        run: | 
          cd ssare
          
  