name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          cd SSARE
          services=(
            "entity_service"
            "geo_service"
            "main_core_app"
            "nlp_service"
            "postgres_service"
            "rag_service"
            "scraper_service"
            "classification_service"
            "liteLLM"
          )
          for service in "${services[@]}"; do
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${service}:${{ github.sha }} -f ./${service}/Dockerfile .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${service}:${{ github.sha }}
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${service}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${service}:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${service}:latest
          done

