name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi  # Optional but recommended
    permissions:
      id-token: write  # Mandatory for Trusted Publishing

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade build

    - name: Build package
      run: |
        cd SSARE/api-client
        python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1