"""Adding top locations and entities to content

Revision ID: ef87360117c8
Revises: ce6bff35eb46
Create Date: 2024-12-25 20:03:55.361557

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'ef87360117c8'
down_revision = 'ce6bff35eb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('contentchunk', sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('image', sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('videoframe', sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videoframe', 'embeddings')
    op.drop_column('image', 'embeddings')
    op.drop_column('contentchunk', 'embeddings')
    op.drop_column('content', 'embeddings')
    # ### end Alembic commands ###